2017.csv
Already in the past, but if anyone is curious
Source: https://2017.pycon.sk/cfp/
=> PyCon SK CfP deadlines

2018.csv
Add PyTennessee to 2018.csv, with thanks! 🎉
=> Add PyTennessee

2018.csv
=> Add PyCon AU 2018

2018.csv
Updated the website URL and sponsor URL for PyCascades.
=> Update PyCascades info

2018.csv
I am one of the organizers of Python Sudeste Brasil. Adding to the list
=> Add Python Sudeste Brasil

2018.csv
The CFP and deadlines are not known yet, I can add them when they become available.
=> Add EuroSciPy 2018

2018.csv
https://pylondinium.org
cc @mariocj89
=> add PyLondinium

2018.csv
add Swiss Python Summit, PyDays Vienna, GeoPython and PyCon DE in 2018
=> added conferences in DE, AT, CH

2019.csv
=> add PyColorado to 2019.csv

2018.csv
So glad I ran into you @ewdurbin. Thanks for teaching me about this repo!
=> Add PyBay to 2018.csv

2018.csv
=> Add PyconFR 2018

2018.csv
Hope this format is alright! We don't have a start/end date figured out just yet.
=> Add 2018 PyCon Canada

2018.csv
It was a Python related event under the FOSDEM umbrella.
=> Add FOSDEMx0 event

.github/ISSUE_TEMPLATE/request-for-access-as-a-conference-organizer-.md, 2017.csv, 2018.csv, 2019.csv, README.md
* Add `Country` column with data for all events
* Add `Venue` column with some data (the ones I knew offhand)
* Updates README to include a description of the fields
Resolves #41
=> Add country and venue columns

2019.csv
=> Add PyCon Spain

2019.csv
=> Add PyCon Latam

2019.csv
Updating DjangoCon US 2019 date and website
=> Updating DjangoCon US 2019 Date and Website

2020.csv
In addition to adding the CSV for 2020, also add the info for PyTN 2020
that we currently have.
=> Add 2020.csv

2019.csv
https://twitter.com/pyconfr/status/1133011925074403328
=> PyCon France 2019

README.md
For readability out of browsers.
=> Wrapping README file

2019.csv
Simply add more missing information with love : ) lint-csv.py validated.
=> PyCon TW: update sponsorship and proposal info

2020.csv
We've just announced the dates for PyCascades 2020 and I'd like to add our conference to the list. 
Thank you 🙏🏼
=> Add PyCascades 2020 details

2019.csv
=> EuroSciPy 2019

2019.csv
=> Add PyCon Korea 2019

2019.csv
=> Add PythonDay México 2019

2020.csv
Add PyOhio 2020 info that's available now
=> Add PyOhio 2020

2020.csv
I have updated the 2020.csv with the PyCon SK conference.
=> Added PyCon SK 2020 conference to the list

2020.csv
cc @frenzymadness @benabraham  -- please ack
=> Add PyCon CZ 2020

2020.csv
PyCon CZ will be 3 days long conference, not three months long marathon :)
Cc @hroncok @benabraham
=> Fix start/end dates for PyCon CZ

2020.csv
We'd like to add PyConWeb conference to the list
=> Add PyConWeb 2020

2020.csv
This PR adds remote.python.pizza 🍕
=> Add Remote Python Pizza

2020.csv
Sorry I messed up the dates for EuroPython earlier :disappointed:
=> Fix EuroPython dates

2020.csv
added Python Pizza New Year's conference.. the last one of the year
=> add last Python Pizza Conference

2021.csv
Add event PyCamp Leipzig 2021.
=> Add PyCamp Leipzig

2021.csv
and sort 2021 chronologically.
=> Add PyCascades, PyCon US, EuroPython 2021

linting/lint-csv.py
Compact the code by using `pathlib` for directory parsing.
=> Use pathlib in lint-csv.py

2023.csv
The CfP is now open, they directly link the Google Doc, so I added that.
=> PyCon Sweden CfP

2023.csv, 2024.csv
=> PyCon Ireland, Indonesia, Pyjamas, DjangoCon Europe

2023.csv, 2024.csv
3 more conferences and an update for Malaysia
=> PyHEP, PackagingCon, Pydata London 24

2020.csv
=> Add PyBeach 2020

2023.csv
=> Add PyOhio 2023

2023.csv, 2024.csv
Found the Python Pizza on Twitter and Chile in the PyCon list
(Lost two Quotation marks, sorry)
=> PyCon Chile & Python Pizza

2024.csv
Update CFP link and add CFP deadline
=> Update PyConFR information

2024.csv
source: https://www.pycon.fr/2024/en/venue.html
=> Update PyConFR information.

2024.csv
Adding a line for PyConZA (South Africa), 3-4 Oct 2024.
=> Add PyConZA

2024.csv
Event details via https://www.pyday.cl/
=> Add PyDay Chile events

2020.csv, 2021.csv, 2022.csv, 2023.csv, 2024.csv
Added all PyBay conference dates
=> [Issue #218] PyBay conference dates

2024.csv
It looks like DjangoCon is still on the old dates.
=> DjangoCon Europe dates moved

2025.csv
=> Add PyCon Estonia 2025

2025.csv
=> Add PyConWeb 2025

2025.csv
and North Bay Python, DjangoCon Europe, DjangoCon Africa, PyOhio
=> Add PyOhio, DjangoCon US, PyCon India, PyCon UK

2025.csv
=> Fix PyCon Greece data

2025.csv
Hi, here's a patch which includes [EuroSciPy 2025](https://euroscipy.org/2025/index.html)!
=> Add EuroSciPy 2025

2025.csv
=> Add PyConFR 2025

2025.csv
=> Add Plone Conference & PyCon Finland

2026.csv
=> Add PyCon Estonia 2026
