python-organizers/conferences

2018.csv
Looking at their CFP page, it ends on Nov 15, 2017.
=> Fix PyCaribbean's CFP end date.

2019.csv
Add dates for PyCaribbean, PyTennessee, and PyCon Colombia 2019
=> Add dates for 2019 conferences

2018.csv
The website url was in the wrong column. It was in the "Talk deadline" column.
=> Fix the url for pycon FR

2018.csv
Doubts:
- https://in.pycon.org/2018/sponsorship_prospectus.pdf is a sponsor URL? Should it be included?
- Should this include the now passed dates for talks CFP?
=> Add PyCon India

2019.csv
Per this [tweet], PyCaribbean talk submissions are open until November 15th.
[tweet]: https://twitter.com/PyCaribbean/status/1061027551353757697
=> Update PyCaribbean talk deadline

.github/ISSUE_TEMPLATE/request-for-access-as-a-conference-organizer-.md, .github/ISSUE_TEMPLATE/request-for-access-as-a-conference-organizer.md, README.md
The readme says that we can grant access to this repo to conference organizer.
But it's not always clear whether someone is a conference organizer or not.
I created this issue template for requesting access to the repo. The idea is to allow a conference organizer to self identify of that they're an organizer and would like access to this project.
=> Create issue template for requesting access as a conference organizer

2019.csv
I was putting together my own list of Python conferences when I came across this repo. I added more conferences where dates and websites for 2019 are known.
- Added PyCon SK (Slovakia)
- Added PyCon Israel
- Added PyCon Russia
- Added SciPy
- Added PyBay
- Added Kiwi PyCon
- Added PyCon UK
- Added PyCon Taiwan
- Added venue and location for Djangocon US
- Fixed a bug in the EuroPython line which had too many columns ([see github's docs on the subject](https://help.github.com/en/articles/rendering-csv-and-tsv-data#handling-errors))
=> Add various pycons with known dates and websites

2019.csv
Hello team!
Was hoping if you could add PyBay 2019 Conference to the Python Conference listings!
**Background information on #PyBay:**
[Pybay](https://pybay.com/) is offered by SF Python, a volunteer-run organization dedicated to building a stronger Python developer community. We do this by organizing fun events that encourage developers to meet like-minded folks, share what they know, and learn from each other. It’s hard work, but seeing people grow and make new friends and connections makes it worth it! We love hearing about companies making hires and migrating to better technologies as a result of our gatherings. We're also grateful to receive support for our work, financially and otherwise. We look forward to delighting you at PyBay and at other SF Python events throughout the year. …
=> Add PyBay 2019 conference

2020.csv
Removed the extra space at the beginning of some fields and use the alpha-3 country code for uniformity with other rows, and added the talk deadline as shown on the website for PyCon Sweden.
=> Remove extra spaces, use alpha-3 country code and add talk deadline for PyCon Sweden

2020.csv
Added EuroPython and Python Web Conf.
In addition to that, I've updated the location and venue for the following conferences for uniformity. Any feedback on the naming is appreciated, I will make the necessary changes.
- Remote Python Pizza
- Scipy 2020
- PyOhio
- PyConline AU
- PyGotham TV
- PyCon India
- PyCon Sweden
Also, DragonPy and ~PyCon ES~ have been postponed to next year. What should 2020.csv reflect in that case? Should these conferences be moved to 2021.csv?
Edit: PyCon ES is not postponed, I initially saw that announcement on the link in 2020.csv: https://2020.es.pycon.org. But it is happening as an online event in October: https://es.python.org/pycones-2020-call-for-proposals-is-open.html
=> Add EuroPython, Python Web Conf and make location/venue uniform

README.md
As written, the readme implies that this repository feeds into www.pycon.org. This change clarifies the fact that the repo here is standalone. For related issues regarding displaying this data, see #89 and #153.
=> Clarify unrelated to pycon.org

2023.csv, linting/lint-csv.py
These rows fail validation via the linting script and rendering on GitHub due to an extra trailing comma. Remove the comma to fix.
This change also slightly modifies the linting script to note which file has failed to pass validation.
=> Remove extra commas from rows in 2023.csv

2023.csv, 2024.csv
This change adds rows for any events that were mentioned during the community announcements lightning talk at PyCon US 2023 (for all events that provided dates and were not already present in the CSV file). Details were taken from slides presented in the talks and from conference websites.
=> Add events announced during PyCon US lightning talks

2023.csv
This date was extended by one day per
https://mastodon.social/@pyconau@fosstodon.org/110302646748961880.
=> Update PyCon AU 2023 CFP due date

2023.csv, 2024.csv
Details taken from each event's website, with the exception of PyCon US 2024, which was taken from
https://speakerdeck.com/mariatta/pyconus2023-closing?slide=29.
=> Add PyCon India, PyConZA, DjangoCon US, and PyCon US

2023.csv
Add the events listed on https://pycon.asia/ that are missing in the list (if they have websites linked). Also add PyCon Estonia.
=> Add PyCon PH, PyCon MY, PyCon Estonia, and PyCon HK

2023.csv
It went public yesterday.
Also GitHub added the trailing newline.
=> Add sponsorship info URL for DjangoCon US 2023

2023.csv, 2024.csv
Hey folks, as mentioned in #89 I was thinking about feeding back my data from https://pythondeadlin.es ( https://gihub.com/JesperDramsch/python-deadlines )
Ran the Linter, and it passed. Here are all the changes:
Modifies:
- FOSDEM +CfP
- PyCon Ph +CfP
- Python Web Conf +CfP
- PyCascades +CfP
- Jupytercon +CfP
- PyCon Lithuania +CfP
- Moscow Conf +CfP
- Pycon IT + Sponsor
- Pydata London +Cfp +Sponsor
- PyCon Israel +CfP
- PyCon Russia +CfP
- PyCon Malaysia +Country
- PyCon TW +CfP
- PyCon CZ was Renamed from old name to PyCon Czechia
- PyCon India +Sponsor +CfP
- Python Brasil +CfP
- PyCon HK +Country
- PyData Tel Aviv +CfP
Added Conferences
- Pydata Seattle
- PyDay La Paz
- PyCon Poland
- PyCon MEA @GlobalDevSlam
- PyCon Slovakia 2024
All the best,
Jesper
=> Add CfPs and other conferences from Pythondeadlin.es

2023.csv
Adds the dates for PyCon Sweden 2023 from the official Python calendar
=> PyCon Sweden 2023

2023.csv
This pull request is to add PyCon Thailand information.
We did modify 2023.csv and passed the default test (python linters/lint-csv.py).
=> PyCon Thailand information

2024.csv
Found a few updates for 2024
Adding:
- Geopython
- PyCon Colombia
- EuroPython
- Scipy US
- Kiwi PyCon
- EARL
- PyCon Estonia
- Swiss Python Summit 
Modifies:
- PyCon DE (sponsor link)
- DjangoCon EU (sponsor link)
=> Adding some conferences for 2024

2024.csv
Heyhey,
I just went through a ton of websites manually to check if they have updates for 2024.
- Add country to PyCon PH
- Add date to PyCon Pakistan
- Add CfP to EuroPython
- Add CfP to Kiwi PyCon
- Add Sponsor to PyCon Estonia
- Scipy just moved around and git diff is struggling I think
- DjangoCon US
- Flask Con
- North Bay
- Piter Py
- Plone Conf
- PyCamp Spain
- PyCon APAC
- PyCon EE
- PyCon ES
- PyCon FR
- PyCon Nigeria
- PyCon PL
- PyCon Russia
- PyData Amsterdam
- PyData Paris
- PyGrunn
- PyHEP
- Python Brasil
- Python Devroom @FOSDEM
- Python fwdays
- Python Niger
- Python Nordeste
- Python Sul Brasil 
- Wagtail Space NL
- Wagtail Space US
They're mostly based on "conferences that were listed before" either here or in the official Python calendar.
Sorry for the massive PR, but I …
=> Update 5, Add 24 Conferences

2024.csv, 2025.csv
Add and update details provided in the PyCon US 2024 lightning talks session for regional Python conferences. These updates include data from the slides presented and the conferences' official websites.
=> Bulk updates from PyCon US 2024 Lightning Talks

2024.csv, 2025.csv
Found a wrong link, so I merged what I had.
Link updates:
- Flask Con
- PyDay Valparaiso
Country updates:
- PyDay Copiapó
- PyDay Valparaiso
- Italy 2025
=> Update some links, remove year from conferences

2024.csv
=> Correct start date PyCon JP 2024

.github/workflows/format.yaml, .github/workflows/validate.yaml, 2025.csv
https://pycon.pyug.at/en/
Also update Python version in GitHub Actions and allow contributors to test their feature branches before opening a PR.
=> Add PyCon Austria 2025

2025.csv
[CFP web page](https://tw.pycon.org/2025/en-us/speaking/cfp) states:
> Conference dates: September 5th, September 7th, 2025
=> adjust PyCon TW dates to match what is on the CFP web page

2025.csv
PyConFI is a special day taking place in cooperation with the longer PloneConf, and a PloneConf ticket gets you access to PyConFI, but you can also buy just a ticket for PyConFI, so I think it makes sense to list these separately.
=> Separate Plone Conference and PyCon Finland

2026.csv
added PythonAsia 2026 to `2026.csv` with dates, location (Malate, Manila, Philippines), venue (De La Salle University Manila), proposal and sponsorship deadlines, and links for the website, proposals, and sponsorships.
=> Add PythonAsia event details to 2026.csv
